### ISSUE TITLE
TUI color palette should be customizable through .glsrc

### ISSUE THREAD

**Issue by ozansz** [ozansz/gls#16]
## Summary

TUI color palette is currently set to constant values in https://github.com/ozansz/gls/blob/main/gui/constants.go. It should be customizable through `.glsrc`

**Comment by gozeloglu** [comment]
I'd like to work on this issue. But, I have a question about it. If the values will be read from the `.glsrc` file, we cannot redeclare constant variables. One solution could be defining variables as `var`, not `const`. What do you think?

**Comment by ozansz** [comment]
Yeah totally, I just forgot to mention that detail
