### ISSUE TITLE
Adding GitHub Actions for tests

### ISSUE THREAD

**Issue by gozeloglu** [ozansz/gls#26]
**Is your feature request related to a problem? Please describe.**

When I open to PR, I always want to see whether my tests are passing. So, a simple GA can be added. 

**Describe the solution you'd like**

I can create a `.yaml` file in [`.github/workflows`](https://github.com/ozansz/gls/tree/main/.github/workflows).

**Comment by ozansz** [comment]
that's a great idea, there were no unit tests in the codebase before but now it has, so there should be a workflow for the tests

**Comment by gozeloglu** [comment]
Can you add a `hacktoberfest` label and assign the issue to me? :))
